from enum import Enum
from collections import namedtuple

# Se asigna el formato a utilizar para el enumerado
TipoError = namedtuple('Error', ['descripcion'])


class TipoErrorEnum(Enum):
    # El formato de nombramiento es: ARCHIVO_ ERROR
    ZIP_NO_EXISTE = TipoError('Existencia')
    ZIP_VACIO = TipoError('Vacio')
    ZIP_EXTENSION_INVALIDA = TipoError('Extensión')
    ZIP_LONGITUD_INVALIDA = TipoError('Longitud')
    ZIP_NOMBRE_NUMERICO = TipoError('Numérico')
    ZIP_ARCHIVO_DUPLICADO = TipoError('Duplicado')
    ZIP_NUMERO_REMISION = TipoError('Remisión')
    ZIP_ARCHIVO_NO_ENCONTRADO = TipoError('No encontrado')
    ZIP_CARPETA = TipoError('Subcarpeta')
    AC_CANTIDAD_CAMPOS = TipoError('Campos')
    AC_LONGITUD_INVALIDA = TipoError('Longitud')
    AC_FORMATO_FECHA = TipoError('Formato fecha')
    AC_NUMERICO = TipoError('Numérico')
    AC_CAMPO_NULO = TipoError('Nulo')
    AH_CANTIDAD_CAMPOS = TipoError('Campos')
    AH_LONGITUD_INVALIDA = TipoError('Longitud')
    AH_FORMATO_FECHA = TipoError('Formato fecha')
    AH_FORMATO_HORA = TipoError('Formato hora')
    AH_CAMPO_NULO = TipoError('Nulo')
    AM_CANTIDAD_CAMPOS = TipoError('Campos')
    AM_LONGITUD_INVALIDA = TipoError('Longitud')
    AM_NUMERICO = TipoError('Numérico')
    AM_CAMPO_NULO = TipoError('Nulo')
    CT_ARCHIVOS_MINIMOS = TipoError('Archivos Incompletos')
    CT_LONGITUD_INVALIDA = TipoError('Longitud')
    CT_LONGITUD_INVALIDA_CODIGO = TipoError('Longitud Codigo Prestador')
    CT_CODIGO_HABILITACION_INVALIDO = TipoError('Codigo Habilitacion')
    CT_NUMERICO = TipoError('Numérico')
    CT_CANTIDAD_CAMPOS = TipoError('Campos')
    CT_ARCHIVOS_EN_ZIP = TipoError('Archivos Referenciados')
    CT_TOTAL_DATOS = TipoError('Total de Datos')
    CT_PREFIJO_ARCHIVO = TipoError('Prefijo')
    CT_CAMPO_NULO = TipoError('Nulo')
    CT_FORMATO_FECHA= TipoError('Formato fecha')
    CT_ARCHIVOS_ZIP_EN_CT=TipoError('Zip en CT')
    AD_CANTIDAD_CAMPOS = TipoError('Campos')
    AD_LONGITUD_INVALIDA = TipoError('Longitud')
    AD_CAMPO_NULO = TipoError('Nulo')
    AD_NUMERICO = TipoError('Numérico')
    AT_CANTIDAD_CAMPOS = TipoError('Campos')
    AT_LONGITUD_INVALIDA = TipoError('Longitud')
    AT_CAMPO_NULO = TipoError('Nulo')
    AT_NUMERICO = TipoError('Numérico')
    AP_CANTIDAD_CAMPOS = TipoError('Campos')
    AP_LONGITUD_INVALIDA = TipoError('Longitud')
    AP_CAMPO_NULO = TipoError('Nulo')
    AP_NUMERICO = TipoError('Numérico')
    AP_FORMATO_FECHA = TipoError('Formato fecha')
    AN_CANTIDAD_CAMPOS = TipoError('Campos')
    AN_LONGITUD_INVALIDA = TipoError('Longitud')
    AN_CAMPO_NULO = TipoError('Nulo')
    AN_NUMERICO = TipoError('Numérico')
    AN_FORMATO_FECHA = TipoError('Formato fecha')
    AF_CANTIDAD_CAMPOS = TipoError('Campos')
    AF_LONGITUD_INVALIDA = TipoError('Longitud')
    AF_CAMPO_NULO = TipoError('Nulo')
    AF_NUMERICO = TipoError('Numérico')
    AF_FORMATO_FECHA = TipoError('Formato fecha')
    AF_GUION_IDENTIFICACION_INVALIDO = TipoError('Numero identificacion con guion')
    AU_CANTIDAD_CAMPOS = TipoError('Campos')
    AU_LONGITUD_INVALIDA = TipoError('Longitud')
    AU_CAMPO_NULO = TipoError('Nulo')
    AU_NUMERICO = TipoError('Numérico')
    AU_FORMATO_FECHA = TipoError('Formato fecha')
    US_CANTIDAD_CAMPOS = TipoError('Campos')
    US_LONGITUD_INVALIDA = TipoError('Longitud')
    US_CAMPO_NULO = TipoError('Nulo')
    US_NUMERICO = TipoError('Numérico')

    # Método para obtener el nombre asignado al enumerado
    @property
    def obtener_descripcion(self):
        return self.value.descripcion
