from enum import Enum
from collections import namedtuple

# Se asigna el formato a utilizar para el enumerado
TipoError = namedtuple('Error', ['descripcion'])


class TipoErrorEnum(Enum):
    # Errores CT
    CT_CODIGO_HABILITACION = TipoError('Codigo habilitación inválido')
    CT_FECHA_REMISION = TipoError('Fecha remision invalida')
    CT_CODIGO_HABILITACION_TOKEN = TipoError('Codigo Habilitacion Token')
    CT_CODIGO_HABILITACION_NO_LISTA= TipoError('Codigo no listas')

    # Errores AD
    AD_NUMERO_FACTURA = TipoError('Factura')
    AD_VALOR_UNITARIO_CANTIDAD = TipoError('Valor unitario')
    AD_VALOR_TOTAL = TipoError("Valor total")
    AD_CODIGO_CONCEPTO = TipoError("Codigo del concepto")

    # Errores AT
    AT_NUMERO_FACTURA = TipoError("Factura no encontrada")
    AT_TIPO_ID = TipoError("Tipo Identificación incorrecto")
    AT_IDENTIFICACION_NO_ENCONTRADA = TipoError("Identificación no encontrada")
    AT_TIPO_IDENTIFICACION_NO_ENCONTRADA = TipoError("Tipo id no encontrada")
    AT_TIPO_SERVICIO = TipoError("Tipo Servicio")
    AT_NOMBRE_SERVICIO = TipoError("Nombre Servicio")
    AT_CANTIDAD_SERVICIO = TipoError("Cantidad Servicio")
    AT_VALOR_UNITARIO = TipoError("Valor unitario")
    AT_VALOR_TOTAL = TipoError("Valor total")
    AT_NUMERO_AUTORIZACION_INCORRECTA = TipoError("Numero autorizacion incorrecta")
    AT_TIPO_SERVICIO_CODIGO=TipoError("Codigo Nulo")
    AT_CODIGO_SERVICIO_NO_CUPS=TipoError("Codigo no cups")
    AT_CODIGO_SERVICIO_NO_VACIO=TipoError("Codigo vacio")
    AT_CODIGO_SERVICIO_NO_TRANSLADO=TipoError("Codigo cups Tras.")
    AT_CODIGO_SERVICIO_NO_ESTANCIA = TipoError("Codigo cups Estan.")
    AT_CODIGO_SERVICIO_EN_AP_AC=TipoError('Condigo en ap o ac')
    AP_NUMERO_AUTORIZACION_VACIA=TipoError("Numero autorizacion vacia")
    # Errores AF
    AF_NUMERO_IDENTIFICACION = TipoError("Número Factura")
    AF_TIPO_ID = TipoError("Tipo Identificación incorrecto")
    AF_NUMERO_FACTURA = TipoError('Factura repetida')
    AF_FECHA_INICIO = TipoError('Fecha inicio')
    AF_FECHA_EXPEDICION = TipoError('Fecha Expedición')
    AF_FECHA_FINAL = TipoError('Fecha final')
    AF_VALOR_NETO = TipoError('Valor neto')
    AF_EAPB_INVALIDO = TipoError('Id EAPB invalido')
    AF_EPS_INVALIDO = TipoError('Id EPS invalido')

    # Errores AM
    AM_FACTURA_NO_ENCONTRADA = TipoError('Factura no encontrada')
    AM_IDENTIFICACION_NO_ENCONTRADA = TipoError('Id no encontrada')
    AM_TIPO_IDENTIFICACION_NO_ENCONTRADA = TipoError('Tipo id no encontrada')
    AM_NOMBRE_GENERICO_VACIO = TipoError('Nombre generico vacio')
    AM_FORMA_FARMACEUTICA_VACIO = TipoError('Forma farmacéutica vacia')
    AM_CONCENTRACION_VACIO = TipoError('Concentración vacio')
    AM_UNIDAD_MEDIDA_VACIO = TipoError('Unidad de medida vacia')
    AM_NUMERO_UNIDADES_VACIO = TipoError('Numero unidades vacio')
    AM_VALOR_UNITARIO_VACIO = TipoError('Valor unitario vacio')
    AM_VALOR_TOTAL_INCORRECTO = TipoError('Valor total incorrecto')
    AM_TIPO_MEDICAMENTO_INCORRECTO = TipoError('Tipo incorrecto')
    AM_NUMERO_AUTORIZACION_INCORRECTA = TipoError("Numero autorizacion incorrecta")

    # Errores AH
    AH_FACTURA_NO_ENCONTRADA = TipoError('Factura no encontrada')
    AH_IDENTIFICACION_NO_ENCONTRADA = TipoError('Id no encontrada')
    AH_TIPO_IDENTIFICACION_NO_ENCONTRADA = TipoError('Tipo id no encontrada')
    AH_VIA_INGRESO_NO_ENCONTRADA = TipoError('Via ingreso no encontrada')
    AH_FECHA_INGRESO_INCORRECTA = TipoError('Fecha ingreso incorrecta')
    AH_FECHA_INGRESO_MAYOR = TipoError('Fecha ingreso mayor')
    AH_CAUSA_EXTERNA_INCORRECTA = TipoError('Causa externa incorrecta')
    AH_ESTADO_SALIDA_INCORRECTA = TipoError('Estado salida incorrecto')
    AH_CAUSA_BASICA_MUERTE_INCORRECTA = TipoError('Causa muerte incorrecta')
    AH_FECHA_EGRESO_INCORRECTA = TipoError('Fecha egreso incorrecta')
    AH_HORA_INGRESO_INCORRECTA = TipoError('Hora ingreso incorrecta')
    AH_DIAGNOSTICO_INGRESO_NO_ENCCONTRADO = TipoError('D ingreso no encontrado')
    AH_DIAGNOSTICO_INGRESO_INCORRECTO = TipoError('D ingreso incorrecto')
    AH_DIAGNOSTICO_EGRESO_NO_ENCCONTRADO= TipoError('D egreso no encontrado')
    AH_SEXO_INCORRECTO = TipoError('Sexo incorrecto')
    AH_DIAGNOSTICO_EGRESO_EDAD_INCORRECTA = TipoError('Edad incorrecto')
    AH_DIAGNOSTICO_EGRESO_SEXO_INCORRECTO = TipoError('Sexo incorrecto')
    AH_EDAD_INCORRECTA = TipoError('Edad incorrecto')
    AH_DIAGNOSTICO_RELACIONADO_1_NO_ENCCONTRADO = TipoError('relacionado1 noencontrado')
    AH_DIAGNOSTICO_RELACIONADO_1_SEXO_INCORRECTO = TipoError('Sexo incorrecto')
    AH_DIAGNOSTICO_RELACIONADO_1_EDAD_INCORRECTA = TipoError('Edad incorrecto')
    AH_DIAGNOSTICO_RELACIONADO_2_NO_ENCCONTRADO = TipoError('relacionado2 noencontrado')
    AH_DIAGNOSTICO_RELACIONADO_2_SEXO_INCORRECTO = TipoError('Sexo incorrecto')
    AH_DIAGNOSTICO_RELACIONADO_2_EDAD_INCORRECTA = TipoError('Edad incorrecto')
    AH_DIAGNOSTICO_RELACIONADO_3_NO_ENCCONTRADO = TipoError('relacionado3 noencontrado')
    AH_DIAGNOSTICO_RELACIONADO_3_SEXO_INCORRECTO = TipoError('Sexo incorrecto')
    AH_DIAGNOSTICO_RELACIONADO_3_EDAD_INCORRECTA = TipoError('Edad incorrecto')
    AH_CAUSA_BASICA_MUERTE_VACIA_O_NO_ENCONTRADA = TipoError('Causa muerte incorrecta')
    AH_CAUSA_BASICA_MUERTE_VACIA_O_NO_ENCONTRADA2 = TipoError('Causa muerte incorrecta 2')
    AH_CAUSA_BASICA_MUERTE_EDAD_INCORRECTA = TipoError('Edad incorrecto')
    AH_CAUSA_BASICA_MUERTE_SEXO_INCORRECTO = TipoError('Sexo incorrecto')
    AH_NUMERO_AUTORIZACION_INCORRECTA = TipoError("Numero autorizacion incorrecta")
    AH_VIA_INGRESO_1=TipoError('Via ingreso 1 fallo')
    AH_VIA_INGRESO_2=TipoError('Via ingreso 2 fallo')
    AH_VIA_INGRESO_4=TipoError('Via ingreso 4 fallo')
    AH_TIPO_IDENTIFICACION_NO_ENCONTRADA_US= TipoError("Tipo id no encontrada ")
    AH_COMPLICACION_MUERTE=TipoError("D complicacion no encontrado")
    AH_COMPLICACION_MUERTE_EDAD_INCORRECTA = TipoError('Edad incorrecto')
    AH_COMPLICACION_MUERTE_SEXO_INCORRECTO = TipoError('Sexo incorrecto')
    AH_CAUSA_EXTERNA_INCORRECTA_PARA_SOAP = TipoError('Causa Externa no Valida para soat')
    # Errores AU
    AU_FACTURA_NO_ENCONTRADA = TipoError('Factura no encontrada')
    AU_IDENTIFICACION_NO_ENCONTRADA = TipoError('Id no encontrada')
    AU_TIPO_IDENTIFICACION_NO_ENCONTRADA = TipoError('Tipo id no encontrada')
    AU_CAUSA_EXTERNA_INCORRECTA = TipoError('Causa externa incorrecta')
    AU_DESTINO_SALIDA_OBSERVACION_INCORRECTO = TipoError('Destino incorrecto')
    AU_DESTINO_SALIDA_OBSERVACION_NO_ENCONTRADO = TipoError('Destino no encontrado')
    AU_ESTADO_SALIDA_INCORRECTA = TipoError('Estado salida incorrecta')
    AU_CAUSA_BASICA_MUERTE_VACIO = TipoError('Causa basica muerte vacio')
    AU_CAUSA_BASICA_MUERTE_INCORRECTA = TipoError('Causa muerte incorrecta')
    AU_CAUSA_BASICA_MUERTE_NO_ENCONTRADA = TipoError('Causamuerte no encontrada')
    AU_FECHA_SALIDA_INCORRECTA = TipoError('Fecha salida incorrecta')
    AU_FECHA_INGRESO_INCORRECTA = TipoError('Fecha ingreso incorrecta')
    AU_HORA_INGRESO_INCORRECTA = TipoError('Hora ingreso incorrecta')
    AU_DIAGNOSTICO_SALIDA_NO_ENCCONTRADO = TipoError('D salida no encontrado')
    AU_DIAGNOSTICO_SALIDA1_NO_ENCCONTRADO = TipoError('relacionado1 noencontrado')
    AU_DIAGNOSTICO_SALIDA2_NO_ENCCONTRADO = TipoError('relacionado2 noencontrado')
    AU_DIAGNOSTICO_SALIDA3_NO_ENCCONTRADO = TipoError('relacionado3 noencontrado')
    AU_SEXO_INCORRECTO = TipoError('Sexo incorrecto')
    AU_SEXO_INCORRECTO_CM = TipoError('Sexo incorrecto CM')
    AU_EDAD_INCORRECTA = TipoError('Edad incorrecto')
    AU_EDAD_INCORRECTA_CM = TipoError('Edad incorrecto CM')
    AU_CAUSA_MUERTE_NO_ENCCONTRADO = TipoError('C muerte no encontrado')
    AU_FECHA_INGRESO_MAYOR_SALIDA= TipoError('Fecha ingreso mayor')
    AU_NUMERO_AUTORIZACION_INCORRECTA = TipoError("Numero autorizacion incorrecta")
    AU_FECHA_INGRESO_SALIDA_INCORRECTO = TipoError('Fecha ingreso y salida incorrectas')
    # Errores AC
    AC_CODIGO_HABILITACION = TipoError('Codigo habilitación inválido ')
    AC_FACTURA_NO_ENCONTRADA = TipoError('Factura no encontrada')
    AC_TIPO_IDENTIFICACION_NO_ENCONTRADA = TipoError('Tipo id no encontrada')
    AC_IDENTIFICACION_NO_ENCONTRADA = TipoError('Id no encontrada')
    AC_FECHA_CONSULTA_INCORRECTA = TipoError('Fecha consulta incorrecta')
    AC_CODIGO_CONSULTA_INCORRECTO = TipoError('Codigo consulta incorrecto')
    AC_FINALIDAD_CONSULTA_INCORRECTA = TipoError('Finalidad consulta incorrecta')
    AC_CAUSA_EXTERNA_INCORRECTA = TipoError('Causa externa incorrecta')
    AC_CODIGO_DIAGNOSTICO_PRINCIPAL_NO_ENCONTRADO = TipoError('Codigo diagnostico principal no encontrado')
    AC_TIPO_DIAGNOSTICO_INCORRECTO = TipoError('Tipo diagnostico incorrecto')
    AC_FINALIDAD_DIAGNOSTICO_1 = TipoError('No es codigo Z')
    AC_FINALIDAD_DIAGNOSTICO_2 = TipoError('Debe ser codigo Z')    
    AC_SEXO_INCORRECTO = TipoError('Sexo incorrecto')
    AC_EDAD_INCORRECTA = TipoError('Edad incorrecto')
    AC_DIAGNOSTICO_PRINCIPAL_NO_ENCONTRADO = TipoError('Codigo diagnostico principal no encontrado')
    AC_DIAGNOSTICO_R1_NO_ENCCONTRADO = TipoError('relacionado1 noencontrado')
    AC_DIAGNOSTICO_R2_NO_ENCCONTRADO = TipoError('relacionado2 noencontrado')
    AC_DIAGNOSTICO_R3_NO_ENCCONTRADO = TipoError('relacionado3 noencontrado')
    AC_NUMERO_AUTORIZACION_INCORRECTA = TipoError("Numero autorizacion incorrecta")
    
    # Errores US
    US_IDENTIFICACION_NO_REPORTADO = TipoError('Id no reportado US')
    US_TIPO_IDENTIFICACION_NO_ENCONTRADA = TipoError('Tipo id no encontrada')
    US_ID_LONGITUD_CC_MS = TipoError('Id invalida CC o MS')
    US_ID_LONGITUD_CE = TipoError('Id invalida CE')
    US_ID_LONGITUD_PA_CD_SC = TipoError('Id invalida PA, CD o SC')
    US_ID_LONGITUD_RC_TI = TipoError('Id invalida RC o TI')
    US_ID_LONGITUD_AS = TipoError('Id invalida AS')
    US_ID_LONGITUD_CN = TipoError('Id invalida CN')
    US_ID_LONGITUD_PE = TipoError('Id invalida PE')
    US_EAPB_INCORRECTO = TipoError('Id EAPB incorrecto')
    US_EAPB_INVALIDO = TipoError('Id EAPB invalido')
    US_TIPO_USUARIO_INVALIDO = TipoError('Tipo usuario invalido')
    US_UNIDAD_MEDIDA_INVALIDA = TipoError('Unidad medida invalida')
    US_EDAD_UNIDAD_MEDIDA_1 = TipoError('Edad y unidad de medida 1 invalida')
    US_EDAD_UNIDAD_MEDIDA_2 = TipoError('Edad y unidad de medida 2 invalida')
    US_EDAD_UNIDAD_MEDIDA_3 = TipoError('Edad y unidad de medida 3 invalida')
    US_TIPO_ID_EDAD_UM_1 = TipoError('TipoId, edad y UM invalida 1')
    US_TIPO_ID_EDAD_UM_2 = TipoError('TipoId, edad y UM invalida 2')
    US_TIPO_ID_EDAD_UM_3 = TipoError('TipoId, edad y UM invalida 3')
    US_TIPO_ID_EDAD_UM_4 = TipoError('TipoId, edad y UM invalida 4')
    US_TIPO_ID_EDAD_UM_5 = TipoError('TipoId, edad y UM invalida 5')
    US_TIPO_ID_EDAD_UM_6 = TipoError('TipoId, edad y UM invalida 6')
    US_TIPO_ID_EDAD_UM_7 = TipoError('TipoId, edad y UM invalida 7')
    US_TIPO_ID_EDAD_UM_8 = TipoError('TipoId, edad y UM invalida 8')
    US_SEXO_INVALIDO = TipoError('Sexo invalido')
    US_DEPARTAMENTO_INVALIDO = TipoError('Departamento invalido')
    US_MUNICIPIO_INVALIDO = TipoError('Municipio invalido')
    US_ZONA_RESIDENCIAL = TipoError('Zona residencial invalida')

    # Errores AP
    AP_CODIGO_HABILITACION = TipoError('Codigo habilitación inválido')
    AP_FACTURA_NO_ENCONTRADA = TipoError('Factura no encontrada')
    AP_TIPO_IDENTIFICACION_NO_ENCONTRADA = TipoError('Tipo id no encontrada')
    AP_IDENTIFICACION_NO_ENCONTRADA = TipoError('Id no encontrada')
    AP_FECHA_PROCEDIMIENTO = TipoError('Fecha incorrecta')
    AP_CUPS_INVALIDO = TipoError('Codigo procedimiento invalido')
    AP_AMBITO_INVALIDO = TipoError('Ambito procedimiento invalido')
    AP_FINALIDAD_PROCEDIMIENTO = TipoError('Finalidad procedimiento invalido')
    AP_PERSONAL_ATIENDE = TipoError('Persona atiende invalido')
    AP_FORMA_QUIRURGICO = TipoError('Forma quirurgico invalido')
    AP_DIAGNOSTICO_NO_ENCONTRADO=TipoError('D proced. no encontrado')
    AP_DIAGNOSTICO_REL1_NO_ENCONTRADO=TipoError('D proced. rel no encontrado')
    AP_SEXO_INCORRECTO = TipoError('Sexo incorrecto')
    AP_EDAD_INCORRECTA = TipoError('Edad incorrecto')
    AP_COMPLICACION_NO_ENCCONTRADO=TipoError("C no encontrada")
    AP_CODIGO_QUIRURGICO=TipoError('Codigo quirurgico')
    AP_NO_QUIRURGICO_CAMPO=TipoError("no quirurgico error")
    AP_NUMERO_AUTORIZACION_INCORRECTA = TipoError("Numero autorizacion incorrecta")

    # Errores AN
    AN_CODIGO_HABILITACION = TipoError('Codigo habilitación inválido')
    AN_FACTURA_NO_ENCONTRADA = TipoError('Factura no encontrada')
    AN_TIPO_ID_MADRE_NO_ENCONTRADA = TipoError('Tipo id no encontrada')
    AN_IDENTIFICACION_NO_ENCONTRADA = TipoError('Id no encontrada')
    AN_FECHA_NACIMIENTO_INCORRECTA = TipoError('Fecha nacimiento incorrecta')
    AN_FECHA_MUERTE_INCORRECTA = TipoError('Fecha muerte incorrecta')
    AN_FECHA_MUERTE_NACIMIENTO_INCORRECTA = TipoError('Fecha muerte nacimiento incorrecta')
    AN_CONTROL_PRENATAL_INCORRECTO = TipoError('Control prenatal incorrecto')
    AN_SEXO_INVALIDO = TipoError('Sexo invalido')
    AN_DIAGNOSTICO_NO_ENCCONTRADO=TipoError("D AN no encontrado")
    AN_SEXO_INCORRECTO = TipoError('Sexo incorrecto')
    AN_EDAD_INCORRECTA = TipoError('Edad incorrecto')
    AN_CAUSA_BASICA_MUERTE_VACIA_O_NO_ENCONTRADA = TipoError('Causa muerte')
    AN_CAUSA_BASICA_MUERTE_VACIA_O_NO_ENCONTRADA2 = TipoError('Causa muerte 2')
    AN_CAUSA_BASICA_MUERTE_EDAD_INCORRECTA = TipoError('Edad incorrecto CM')
    AN_CAUSA_BASICA_MUERTE_SEXO_INCORRECTO = TipoError('Sexo incorrecto CM')
    AN_INCONSISTENCIA_MUERTE = TipoError('Inconsistencia muerte')
    AN_FECHA_HORA_MUERTE_INVALIDA = TipoError('Fecha y hora de muerte invalida')

    @property
    def obtener_descripcion(self):
        return self.value.descripcion
